### ISSUE TITLE
Popup confirmation for order submission

### ISSUE THREAD

**Issue by ls3233** [gabriellet/thepriceisright#7] opened 2016-10-26 22:46 UTC
When submitting a new order, there's a chance that a user could "fat finger" the order details e.g. sell 100k instead of 10k. We need to include a confirmation popup so users can verify their order information before submission.

**Comment by gabriellet** [comment] 2016-10-26 23:25
Is this a duplicate of #6?

**Closed as completed** 2016-11-10 03:50 UTC
Labels: v1.5-demo
